- hosts: all
  vars:
  tasks:
  - name: Run Updates
    package:
      name: '*'
      state: latest
    become: true
  - name: Install init Packages
    package:
      name: unzip
      state: present
    become: true
    with_items:
      - unzip
      - vim
      - bind-utils